[project]
name = "glowing-octo-fishstick"
version = "0.1.0"
description = "GitHub Actions practice repository"
readme = "README.md"
requires-python = ">=3.10"

[dependency-groups]
dev = [
    "toml>=0.10.2",
    "typer>=0.16.0",
]
